# Generated by Django 5.2.6 on 2025-09-08 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangarin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priotrity',
            new_name='priority',
        ),
    ]
