# Generated by Django 5.2.6 on 2025-09-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangarin', '0002_rename_priotrity_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorties'},
        ),
    ]
